server:
   port: 9001

spring:
   kafka:
      topics:
         -
            name: show-seat
            num-partitions: 1
            replication-factor: 1
         -
            name: booking
            num-partitions: 1
            replication-factor: 1
         -
            name: ticket
            num-partitions: 1
            replication-factor: 1
      